language: python

python:
  - "2.7"

cache: apt

install: "pip install -r requirements.txt --use-mirrors"


before_install:
  - sudo apt-get update
  - sudo apt-get install python-pygame
  - sudo apt-get install libasound2-dev alsa-utils alsa-oss
  - sudo modprobe snd-dummy

script:
  - python testdog.py

virtualenv:
  system_site_packages: true
