language: python

python:
  - "2.7"

cache: apt

install: "pip install -r .requirements --use-mirrors"


before_install:
  - sudo apt-get update
  - sudo apt-get install python-pygame

script:
  - python testdog.py

virtualenv:
  system_site_packages: true
